import type { UploadType } from "@/types/database";

const METADATA_LINE =
  /^(transcript|meeting transcript|notes by|powered by|generated by|summary|participants|attendees|date:|time:|duration:|meeting id|join time|leave time|exported from|fireflies|otter\.ai|zoom|google meet)/i;

const ZOOM_LINE =
  /^(\d{1,2}:\d{2}:\d{2})\s+(.+?):\s*(.+)$/;

const TIMESTAMP_PREFIX =
  /^(\d{1,2}:\d{2}(?::\d{2})?(?:[.,]\d{1,3})?)\s+(.+)$/;

export function detectMeetingExportType(
  filename: string,
  text: string,
): UploadType | null {
  const lower = filename.toLowerCase();
  const head = text.slice(0, 2000).toLowerCase();

  if (lower.includes("otter") || head.includes("otter.ai")) return "otter";
  if (lower.includes("fireflies") || head.includes("fireflies")) return "fireflies";
  if (lower.includes("zoom") || head.includes("zoom meeting")) return "zoom";
  if (
    lower.includes("meet") ||
    head.includes("google meet") ||
    head.includes("meet.google.com")
  ) {
    return "meet";
  }

  if (/\d{1,2}:\d{2}:\d{2}\s+[A-Za-z].+?:/.test(text)) return "zoom";

  return null;
}

export function cleanMeetingExportText(text: string): string {
  const lines = text.split(/\r?\n/);
  const cleaned: string[] = [];

  for (const line of lines) {
    let trimmed = line.trim();
    if (!trimmed) {
      cleaned.push("");
      continue;
    }

    if (METADATA_LINE.test(trimmed)) continue;
    if (/^={3,}$/.test(trimmed) || /^-{3,}$/.test(trimmed)) continue;

    const zoomMatch = trimmed.match(ZOOM_LINE);
    if (zoomMatch) {
      trimmed = `${zoomMatch[2].trim()}: ${zoomMatch[3].trim()}`;
    } else {
      const tsMatch = trimmed.match(TIMESTAMP_PREFIX);
      if (tsMatch && !trimmed.includes(":")) {
        trimmed = tsMatch[2].trim();
      } else if (tsMatch && /:\s/.test(trimmed)) {
        trimmed = trimmed.replace(/^\d{1,2}:\d{2}(?::\d{2})?(?:[.,]\d{1,3})?\s+/, "");
      }
    }

    trimmed = trimmed.replace(/^\[[\d:]+\]\s*/, "");
    trimmed = trimmed.replace(/^\([\d:]+\)\s*/, "");

    if (trimmed) cleaned.push(trimmed);
  }

  return cleaned.join("\n");
}
